# -*- coding: utf-8 -*-
"""Imersão Python - aula 03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O4IlqUg2sXK5e5RnFp2MAOkbfyOm5njQ
"""

import pandas as pd

df_principal = pd.read_excel("/content/Imersão Python - Tabela de ações - #01.xlsx",sheet_name="Principal")
df_principal.head(11)

df_total_de_acoes = pd.read_excel("/content/Imersão Python - Tabela de ações - #01.xlsx",sheet_name="Total_de_acoes")
df_total_de_acoes.head(11)

df_tickets = pd.read_excel("/content/Imersão Python - Tabela de ações - #01.xlsx",sheet_name="Ticker")
df_tickets.head(11)

df_chatgpt = pd.read_excel("/content/Imersão Python - Tabela de ações - #01.xlsx",sheet_name="Chatgpt")
df_chatgpt.head(11)

df_principal=df_principal[['Ativo','Data','Último (R$)','Var. Dia (%)']].copy()
df_principal

df_principal=df_principal.rename(columns={'Último (R$)':'valor_final','Var. Dia (%)':'var_dias_pct'}).copy()
df_principal

df_principal['var_pct']=df_principal['var_dias_pct']/100
df_principal['valor_inicial']=df_principal['valor_final']/(df_principal['var_pct']+1)
df_principal

df_principal=df_principal.merge(df_total_de_acoes,left_on='Ativo',right_on='Código',how='left')
df_principal

df_principal= df_principal.drop(columns=['Código','Var_pct'])
df_principal

df_principal=df_principal.rename(columns={'Qtde. Teórica':'Qtde_Teorica'}).copy()
df_principal

df_principal['variacao_rs']= (df_principal['valor_final']-df_principal['valor_inicial'])*df_principal['Qtde_Teorica']
df_principal

pd.options.display.float_format = "{:.2f}".format
df_principal

df_principal['Qtde_Teorica'] = df_principal['Qtde_Teorica'].astype(int)
df_principal

df_principal['resultado']  = df_principal['variacao_rs'].apply(lambda x: 'subiu' if x > 0 else ('desceu' if x < 0 else 'estavel'))

df_principal

df_principal = df_principal.merge(df_tickets,left_on='Ativo',right_on='Ticker',how='left')
df_principal

df_principal= df_principal.drop(columns=['Ticker'])
df_principal

df_principal = df_principal.merge(df_chatgpt,left_on='Nome',right_on='Nome da Empresa',how='left')
df_principal

df_principal=df_principal.rename(columns={'Nome da Empresa':'nome_empresa','Idade em anos':'idade_anos'}).copy()
df_principal

df_principal= df_principal.drop(columns=['Nome'])
df_principal

df_principal['categ_idade'] = np.where(df_principal['idade_anos'] > 100, 'maior que 100', np.where(df_principal['idade_anos'] < 50, 'menor que 50', 'entre 50 e 100'))
df_principal

# Calculando o maior valor
maior = df_principal['variacao_rs'].max()

# Calculando o menor valor
menor = df_principal['variacao_rs'].min()

# Calculando a média
media = df_principal['variacao_rs'].mean()

# Calculando a média de quem subiu
media_subiu = df_principal[df_principal['resultado'] == 'subiu']['variacao_rs'].mean()

# Calculando a média de quem desceu
media_desceu = df_principal[df_principal['resultado'] == 'desceu']['variacao_rs'].mean()

# Imprimindo os resultados
print(type(maior))
#print(f"Maior: {float(maior):,.2f}")
#print(f"Menor: {float(menor):,.2f}")
#print(f"Média: {float(media):,.2f}")
#print(f"Média de quem subiu: {float(media_subiu):,.2f}")
#print(f"Média de quem desceu: {float(media_desceu):,.2f}")

